services:
  - type: web
    name: misiuni-soferi-postgres
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python main.py
    envVars:
      - key: PYTHON_VERSION
        value: "3.11.0"
      - key: DATABASE_URL
        value: "postgresql://misiuni_soferi_3ld2_user:Wcn2FhzXbRfSwAMyy80TX5lkpn8clrKS@dpg-d3vab93e5dus73a86hcg-a/misiuni_soferi_3ld2"
